Make it easier to add --cflags/--libs to a setuptools Extension.
matze/pkgconfig pull request #49
Opened 2020-12-17 00:45 UTC by anntzer

The previous solution was to use `parse()` with something like
`Extension("foo", ["foo.c"], **parse(...))`, but

1) that would not work if there are other include dirs (etc.) that
   needed to be passed manually, in which case one had to look oneself
   over the dict entries
   (`ext = Extension(..., libraries=["manualentry"])`
   `for k, v in parse(...).items(): getattr(ext, k).extend(v)`)

2) some flags are not parsed correctly (e.g. `--fopenmp`, #38), but for the
   specific use-case of setuptools Extensions, we don't care about flag
   semantics, we can just mindlessly dump everything into
   `extra_{compile,link}_args`.

2021-03-18 09:32 UTC, anntzer commented
Kindly bumping?

2021-03-18 21:28 UTC, matze requested changes

2021-03-18 21:28 UTC, matze commented
Sorry, I wrote that comment months ago but never pressed "submit" … :see_no_evil:

2021-03-19 08:27 UTC, anntzer commented on pkgconfig/pkgconfig.py
> +        re.split(r'(?<!\\) ', cflags.replace('\\"', '')))
fair point, fixed.

2021-03-19 19:56 UTC, merged

2021-03-19 19:56 UTC, matze commented
Thanks. And again, sorry for the delay.

2021-03-19 20:36 UTC, anntzer commented
No worries.

2021-06-02 12:12 UTC, anntzer commented
Any chance for a new release including this?
Thanks!

2021-06-02 21:19 UTC, matze commented
Yes, will do tomorrow!